services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9000:9000"  # Native интерфейс
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: chatbot
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    # platform: linux/amd64
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: sna-zookeeper
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:7.1.0
    # platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    container_name: sna-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
volumes:
  clickhouse_data:

  zookeeper_data:
  # driver: local
  # driver_opts:
  #   type: none
  #   o: bind
  #   device: ./volumes/kafka/zookeeper_data
  zookeeper_log:
  # driver: local
  # driver_opts:
  #   type: none
  #   o: bind
  #   device: ./volumes/kafka/zookeeper_log
  broker_data:
